### ISSUE TITLE
Automated Unit Tests Execution

### ISSUE THREAD

**Issue by nicolasaceroe** [CSCI-GA-2820-SP24-001/orders#62] opened 2024-04-03 01:52 UTC
**As a** developer, 
**I want** automated unit tests to be executed upon every code commit, 
**So that** I can ensure code quality and prevent regressions.

**Details and Assumptions**

Unit tests should be automatically triggered. 

**Acceptance Criteria**

Given a codebase with automated unit tests,
When the CD pipeline is triggered,
Then the pipeline executes automated unit tests as part of the build process.
Then the pipeline fails the build if any unit tests fail.

**Comment by frybin** [comment] 2024-04-16 19:10
Duplicate of #42

**Closed as completed by frybin** 2024-04-16 19:10 UTC
Labels: enhancement
